# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toolbox.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(541, 786)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_openfile = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_openfile.sizePolicy().hasHeightForWidth())
        self.groupBox_openfile.setSizePolicy(sizePolicy)
        self.groupBox_openfile.setObjectName("groupBox_openfile")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_openfile)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit_eegfile = QtWidgets.QLineEdit(self.groupBox_openfile)
        self.lineEdit_eegfile.setObjectName("lineEdit_eegfile")
        self.gridLayout_4.addWidget(self.lineEdit_eegfile, 0, 1, 1, 1)
        self.pushButton_openfile = QtWidgets.QPushButton(self.groupBox_openfile)
        self.pushButton_openfile.setObjectName("pushButton_openfile")
        self.gridLayout_4.addWidget(self.pushButton_openfile, 0, 0, 1, 1)
        self.pushButton_openxz = QtWidgets.QPushButton(self.groupBox_openfile)
        self.pushButton_openxz.setObjectName("pushButton_openxz")
        self.gridLayout_4.addWidget(self.pushButton_openxz, 2, 0, 1, 1)
        self.lineEdit_xyz = QtWidgets.QLineEdit(self.groupBox_openfile)
        self.lineEdit_xyz.setObjectName("lineEdit_xyz")
        self.gridLayout_4.addWidget(self.lineEdit_xyz, 2, 1, 1, 1)
        self.comboBox_montage = QtWidgets.QComboBox(self.groupBox_openfile)
        self.comboBox_montage.setEnabled(True)
        self.comboBox_montage.setEditable(False)
        self.comboBox_montage.setDuplicatesEnabled(False)
        self.comboBox_montage.setObjectName("comboBox_montage")
        self.comboBox_montage.addItem("")
        self.comboBox_montage.addItem("")
        self.comboBox_montage.addItem("")
        self.comboBox_montage.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_montage, 1, 1, 1, 1)
        self.label_montage = QtWidgets.QLabel(self.groupBox_openfile)
        self.label_montage.setObjectName("label_montage")
        self.gridLayout_4.addWidget(self.label_montage, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_openfile)
        self.groupBox_setparameters = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_setparameters.setObjectName("groupBox_setparameters")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_setparameters)
        self.gridLayout.setObjectName("gridLayout")
        self.label_compute = QtWidgets.QLabel(self.groupBox_setparameters)
        self.label_compute.setObjectName("label_compute")
        self.gridLayout.addWidget(self.label_compute, 4, 0, 1, 1)
        self.groupBox_advancedparameters = QtWidgets.QGroupBox(self.groupBox_setparameters)
        self.groupBox_advancedparameters.setCheckable(True)
        self.groupBox_advancedparameters.setObjectName("groupBox_advancedparameters")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_advancedparameters)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_randomseed = QtWidgets.QLabel(self.groupBox_advancedparameters)
        self.label_randomseed.setObjectName("label_randomseed")
        self.gridLayout_2.addWidget(self.label_randomseed, 0, 0, 1, 1)
        self.spinBox_seed = QtWidgets.QSpinBox(self.groupBox_advancedparameters)
        self.spinBox_seed.setMaximum(9999)
        self.spinBox_seed.setObjectName("spinBox_seed")
        self.gridLayout_2.addWidget(self.spinBox_seed, 0, 1, 1, 1)
        self.label_maxiter = QtWidgets.QLabel(self.groupBox_advancedparameters)
        self.label_maxiter.setObjectName("label_maxiter")
        self.gridLayout_2.addWidget(self.label_maxiter, 1, 0, 1, 1)
        self.label_maxpcacomponents = QtWidgets.QLabel(self.groupBox_advancedparameters)
        self.label_maxpcacomponents.setObjectName("label_maxpcacomponents")
        self.gridLayout_2.addWidget(self.label_maxpcacomponents, 0, 2, 1, 1)
        self.label_npcacomponents = QtWidgets.QLabel(self.groupBox_advancedparameters)
        self.label_npcacomponents.setObjectName("label_npcacomponents")
        self.gridLayout_2.addWidget(self.label_npcacomponents, 1, 2, 1, 1)
        self.spinBox_maxiter = QtWidgets.QSpinBox(self.groupBox_advancedparameters)
        self.spinBox_maxiter.setMinimum(1)
        self.spinBox_maxiter.setMaximum(9999)
        self.spinBox_maxiter.setObjectName("spinBox_maxiter")
        self.gridLayout_2.addWidget(self.spinBox_maxiter, 1, 1, 1, 1)
        self.spinBox_maxpcacomponents = QtWidgets.QSpinBox(self.groupBox_advancedparameters)
        self.spinBox_maxpcacomponents.setWrapping(False)
        self.spinBox_maxpcacomponents.setAccelerated(True)
        self.spinBox_maxpcacomponents.setMinimum(2)
        self.spinBox_maxpcacomponents.setMaximum(9999)
        self.spinBox_maxpcacomponents.setObjectName("spinBox_maxpcacomponents")
        self.gridLayout_2.addWidget(self.spinBox_maxpcacomponents, 0, 3, 1, 1)
        self.spinBox_npcacomponents = QtWidgets.QSpinBox(self.groupBox_advancedparameters)
        self.spinBox_npcacomponents.setMinimum(1)
        self.spinBox_npcacomponents.setMaximum(9999)
        self.spinBox_npcacomponents.setObjectName("spinBox_npcacomponents")
        self.gridLayout_2.addWidget(self.spinBox_npcacomponents, 1, 3, 1, 1)
        self.gridLayout.addWidget(self.groupBox_advancedparameters, 2, 0, 1, 2)
        self.label_ncomponents = QtWidgets.QLabel(self.groupBox_setparameters)
        self.label_ncomponents.setObjectName("label_ncomponents")
        self.gridLayout.addWidget(self.label_ncomponents, 1, 0, 1, 1)
        self.pushButton_compute = QtWidgets.QPushButton(self.groupBox_setparameters)
        self.pushButton_compute.setObjectName("pushButton_compute")
        self.gridLayout.addWidget(self.pushButton_compute, 3, 0, 1, 2)
        self.comboBox_methods = QtWidgets.QComboBox(self.groupBox_setparameters)
        self.comboBox_methods.setObjectName("comboBox_methods")
        self.comboBox_methods.addItem("")
        self.comboBox_methods.addItem("")
        self.comboBox_methods.addItem("")
        self.comboBox_methods.addItem("")
        self.gridLayout.addWidget(self.comboBox_methods, 0, 1, 1, 1)
        self.label_method = QtWidgets.QLabel(self.groupBox_setparameters)
        self.label_method.setObjectName("label_method")
        self.gridLayout.addWidget(self.label_method, 0, 0, 1, 1)
        self.spinBox_ncomponents = QtWidgets.QSpinBox(self.groupBox_setparameters)
        self.spinBox_ncomponents.setMinimum(2)
        self.spinBox_ncomponents.setMaximum(9999)
        self.spinBox_ncomponents.setObjectName("spinBox_ncomponents")
        self.gridLayout.addWidget(self.spinBox_ncomponents, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_setparameters)
        self.groupBox_plot = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_plot.setObjectName("groupBox_plot")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_plot)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_plotsources = QtWidgets.QPushButton(self.groupBox_plot)
        self.pushButton_plotsources.setObjectName("pushButton_plotsources")
        self.gridLayout_3.addWidget(self.pushButton_plotsources, 0, 0, 1, 1)
        self.pushButton_plottopomaps = QtWidgets.QPushButton(self.groupBox_plot)
        self.pushButton_plottopomaps.setObjectName("pushButton_plottopomaps")
        self.gridLayout_3.addWidget(self.pushButton_plottopomaps, 0, 1, 1, 1)
        self.pushButton_plotoverlay = QtWidgets.QPushButton(self.groupBox_plot)
        self.pushButton_plotoverlay.setObjectName("pushButton_plotoverlay")
        self.gridLayout_3.addWidget(self.pushButton_plotoverlay, 1, 0, 1, 1)
        self.pushButton_plotcorrelationmatrix = QtWidgets.QPushButton(self.groupBox_plot)
        self.pushButton_plotcorrelationmatrix.setObjectName("pushButton_plotcorrelationmatrix")
        self.gridLayout_3.addWidget(self.pushButton_plotcorrelationmatrix, 1, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_plot)
        self.groupBox_apply = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_apply.setObjectName("groupBox_apply")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_apply)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_apply = QtWidgets.QPushButton(self.groupBox_apply)
        self.pushButton_apply.setObjectName("pushButton_apply")
        self.verticalLayout_2.addWidget(self.pushButton_apply)
        self.label_apply = QtWidgets.QLabel(self.groupBox_apply)
        self.label_apply.setObjectName("label_apply")
        self.verticalLayout_2.addWidget(self.label_apply)
        self.verticalLayout.addWidget(self.groupBox_apply)
        self.groupBox_save = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_save.setObjectName("groupBox_save")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_save)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_save = QtWidgets.QPushButton(self.groupBox_save)
        self.pushButton_save.setObjectName("pushButton_save")
        self.verticalLayout_4.addWidget(self.pushButton_save)
        self.label_save = QtWidgets.QLabel(self.groupBox_save)
        self.label_save.setObjectName("label_save")
        self.verticalLayout_4.addWidget(self.label_save)
        self.verticalLayout.addWidget(self.groupBox_save)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ICA toolbox"))
        self.groupBox_openfile.setTitle(_translate("MainWindow", "Open File"))
        self.pushButton_openfile.setText(_translate("MainWindow", "Data file"))
        self.pushButton_openxz.setText(_translate("MainWindow", "Location file"))
        self.comboBox_montage.setItemText(0, _translate("MainWindow", "standard_1005"))
        self.comboBox_montage.setItemText(1, _translate("MainWindow", "biosemi128"))
        self.comboBox_montage.setItemText(2, _translate("MainWindow", "GSN-HydroCel-257"))
        self.comboBox_montage.setItemText(3, _translate("MainWindow", "From file"))
        self.label_montage.setText(_translate("MainWindow", "Montage"))
        self.groupBox_setparameters.setTitle(_translate("MainWindow", "Parameters"))
        self.label_compute.setText(_translate("MainWindow", "None"))
        self.groupBox_advancedparameters.setTitle(_translate("MainWindow", "Advanced Parameters"))
        self.label_randomseed.setText(_translate("MainWindow", "random_seed"))
        self.label_maxiter.setText(_translate("MainWindow", "max_iter "))
        self.label_maxpcacomponents.setText(_translate("MainWindow", "max_pca_components "))
        self.label_npcacomponents.setText(_translate("MainWindow", "n_pca_components "))
        self.label_ncomponents.setText(_translate("MainWindow", "n components"))
        self.pushButton_compute.setText(_translate("MainWindow", "Compute"))
        self.comboBox_methods.setItemText(0, _translate("MainWindow", "fastica"))
        self.comboBox_methods.setItemText(1, _translate("MainWindow", "infomax"))
        self.comboBox_methods.setItemText(2, _translate("MainWindow", "extended-infomax"))
        self.comboBox_methods.setItemText(3, _translate("MainWindow", "picard"))
        self.label_method.setText(_translate("MainWindow", "Method:"))
        self.groupBox_plot.setTitle(_translate("MainWindow", "Plot"))
        self.pushButton_plotsources.setText(_translate("MainWindow", "Plot sources"))
        self.pushButton_plottopomaps.setText(_translate("MainWindow", "Plot topomaps"))
        self.pushButton_plotoverlay.setText(_translate("MainWindow", "Plot overlay"))
        self.pushButton_plotcorrelationmatrix.setText(_translate("MainWindow", "Plot Correlation Matrix"))
        self.groupBox_apply.setTitle(_translate("MainWindow", "Apply"))
        self.pushButton_apply.setText(_translate("MainWindow", "Apply"))
        self.label_apply.setText(_translate("MainWindow", "None"))
        self.groupBox_save.setTitle(_translate("MainWindow", "Save"))
        self.pushButton_save.setText(_translate("MainWindow", "Save"))
        self.label_save.setText(_translate("MainWindow", "None"))

